### ISSUE TITLE
Using multiple version at the same time

### ISSUE THREAD

**Issue by henningwerner** [fpoirotte/phpfarm#13]
Hi,

I want to use phpfarm to running multiple PHP versions at the same time.
Can you explain me this procedure?

Thanks!

**Comment by nenadalm** [comment]
hi. Is there something unclear in the readme: https://github.com/fpoirotte/phpfarm? Your question doesn't seems to be very specific about what you want to achieve and what your current status is.

**Comment by matthew-dean** [comment]
>  Is there something unclear in the readme

@nenadalm Yes. That documentation covers everything about _installing_ phpfarm, but, strangely, doesn't seem to say anything about how to actually use it. That is, how to set `/website-A` to PHP 5, and `/website-B` to PHP 7, where both folders are local paths to that machine. So, I had the same question.

**Comment by matthew-dean** [comment]
For example, does `src/custom/php.ini` in the "PHP.ini customization" section imply that a particular PHP file needs to be placed in a site folder of `src/`, that will effectively switch the version? Do you need `php.ini` in addition to a `php-5.ini`? Or do these `php.ini` files go somewhere else and have nothing to do with setting the version of PHP that is used to interpret a folder's `.php` files? Or are these files just something that are created by a build script which you rename to a `php.ini`, which is implied goes into a particular folder?

So, the current docs are sort of list of ingredients for pizza, but not how to make pizza.

**Comment by fpoirotte** [comment]
Hi,

phpfarm is primarily meant as a tool to build (compile) multiple versions of PHP, and that's what the readme covers. It doesn't cover usage with respect to a specific webserver because the exact steps required to load PHP into the webserver vary greatly depending on what software you use. Also, phpfarm is not necessarily meant to be used in a web context. For example, I personally use phpfarm from the command-line only, to run unit tests, static analysis, etc. through a continuous integration system.

Nonetheless, phpfarm builds the following PHP binaries by default:
* "php" (aka. "php-cli"): the command-line interface (CLI) to the PHP interpreter
* "php-cgi": a FastCGI interface to PHP
* "php-fpm" (only for PHP 5.4+ due to a limitation in PHP 5.3.x): the PHP FastCGI Pool Manager, meant to ease management of FastCGI processes

Depending on what webserver you're using, you can either:
* load the php-cgi binary for each version you want to use into the webserver, and then use file type associations or other methods like environment variables to indicate which version should be used to serve a particular script
* run a separate php-fpm pool for each PHP version and then use file type associations or another method to make your webserver handle requests through a certain pool

Refer to http://php.net/manual/en/install.php and your webserver's documentation for more information on how to load the PHP interpreter into the webserver.

On another note, the php-5.ini files you were referring to are used to generate the final php.ini file used by PHP when running in CLI or CGI mode. They are not related to selecting the version your webservice will use to serve files in any way. See http://php.net/manual/en/ini.php for more information on the contents of that file.

Finally, if you have never built, configured & installed PHP from source before, I recommend that you read the documentation on the official PHP website first.

**Comment by matthew-dean** [comment]
Fair enough. Thanks for answering.

**Comment by fpoirotte** [comment]
Closing based on previous comments.
