### ISSUE TITLE
PHP7 does not compile on arm64

### ISSUE THREAD

**Issue by mmalisz** [fpoirotte/phpfarm#19]
[aarch64-build-fix.patch.txt](https://github.com/fpoirotte/phpfarm/files/1211417/aarch64-build-fix.patch.txt)
Hi there,

there is an issue with compiling PHP7 (tested on 7.1.4 and 7.1.8) on arm64 platforms (I own Odroid C2).
I've found somewhere a patch for Zend/zend_multiply.h, which fixes that issue.
It would be great if you could apply that patch automaticaly if arm64 is detected.

**Comment by fpoirotte** [comment]
Hello,

Thank you for reporting the issue here.
However, since the problem lies in PHP itself rather than in phpfarm, I'm reluctant to add such a patch directly into phpfarm. In addition, I'm unsure whether detecting arm64 platforms would be easy, and I do not possess the necessary hardware to test this.

Instead, I suggest that you use a customization folder to manage the patch.
This involves creating a folder named ``custom`` at the root of phpfarm (where the ``src/`` folder lies) and creating various files there. For your use case, adding an ``options.sh`` file with a call to ``patch`` should be enough.

Applying the patch from the ``options.sh`` file usually involves the following code snippet:
```
#!/bin/bash

# Move to the folder used to compile the version
pushd "php-$1"

# Apply the patch
patch -r - -N -p1 < ../custom/core-constants.diff

# Return to the original folder
popd
```

On systems where bash (and hence, pushd/popd) is not available, ``cd "php-$1"`` & ``cd -`` can be used instead to move back and forth between the folders.

The README has more information on the various files in the ``custom/`` folder.
See also [this repository](https://github.com/Erebot/Erebot_farm/blob/master/options.sh) for an example usage of the strategy I described here.

**Comment by mmalisz** [comment]
Thanks for your suggestions.
I think this issue can be closed, however, I'll leave it to you.
