### ISSUE TITLE
GPG key for PHP 8.1 is missing

### ISSUE THREAD

**Issue by aschuch247** [fpoirotte/phpfarm#29]
Compiling PHP 8.1 using phpfarm does not work as the GPG key for PHP 8.1 is not available. Can you please add it?

**Comment by fpoirotte** [comment]
Hi,

I've added the GPG keys for PHP 8.1 / 8.2.
I've also added the URLs required to download alpha/beta/RC versions of PHP 8.1 / 8.2.

Please note however that PHPFarm is not actively maintained anymore and that these versions have not been tested.
Hence, you will have to work around any bug you find by yourself.

Instead, I recommend switching over to your distribution's packages because nowadays most Linux distributions provide access to multiple PHP versions:
* Debian provides versioned packages (php7.4, php8.1, etc.)
* Fedora / EL can use Remi Collet's repository (https://rpms.remirepo.net/wizard/)
* etc.
